language: cpp

sudo: false

compiler:
 - g++

addons:
  apt:
    packages:
          - libboost-all-dev
          - libpython-dev
          - scons
          - python2.7


script:	scons

notifications:
  email: false
