Import('env')
Import('libs')
import glob

libs_sources = map(lambda x: Glob(x + '/*.cpp'), libs)
program_sources = ['#src/Main.cpp']

for i in range(len(libs)):
    env['SHARED_LIBS'].append(env.Library(libs[i],libs_sources[i], LIBS=env['EXTERNAL_LIBS']))

app = env.Program("../app", program_sources, LIBS=env['SHARED_LIBS']+env['EXTERNAL_LIBS'])
env.Depends(app, env['SHARED_LIBS'])

Default(app)

Export('env')
Return('app')
